name: matematicasuperpiatta
version: 1.2.0
summary: Matematica Superpiatta
description: |
  Videogioco per insegnamento e apprendimento della matematica.
confinement: strict
base: core22

parts:
  matematicasuperpiatta:
    plugin: cmake
    cmake-parameters:
      - -DRUN_IN_PLACE=FALSE
      - -DCMAKE_BUILD_TYPE=Release
    source-type: local
    source: .
    build-packages:
      - g++
      - make
      - cmake
      - libc6-dev
      - libpng-dev
      - libjpeg-dev
      - libxi-dev
      - libgl1-mesa-dev
      - libsqlite3-dev
      - libogg-dev
      - libvorbis-dev
      - libopenal-dev
      - libcurl4-gnutls-dev
      - libfreetype6-dev
      - zlib1g-dev
      - libgmp-dev
      - libjsoncpp-dev
      - libzstd-dev
      - libluajit-5.1-dev
      - gettext
      - libpq-dev
    stage-packages:
      - libc6
      - libstdc++6
      - libpq-dev
      #- libcurl4
      #- libcurl3-gnutls
      #- libldap-2.5-0
      #- libnghttp2-14
      #- libpsl-dev
      #- librtmp1
      #- libsasl2-2
      #- libx11-dev
      #- libxi-dev
      #- libjpeg-dev
      #- libjsoncpp-dev
      #- libopenal-dev
      #- libpq-dev
      #- libvorbis-dev

apps:
  matematicasuperpiatta:
    command: usr/local/bin/minetest
    extensions: [gnome]
    plugs:
      - x11
      - opengl
      - network
      - network-bind
      - audio-playback
      - joystick
